fetch: blake2s1.js inferno.js inferno-create-element.js

blake2s1.js:
	curl -L -O https://github.com/imuli/treehash/raw/master/blake2s1.js
inferno.js:
	curl -L -O https://unpkg.com/inferno@3.10.1/dist/inferno.js
inferno-create-element.js:
	curl -L -O https://unpkg.com/inferno-create-element@3.10.1/dist/inferno-create-element.js

clean:
	rm -f blake2s1.js inferno.js inferno-create-element.js
